[package]
name = "node-primitives"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
primitives = { package = "substrate-primitives",  git = "https://github.com/paritytech/substrate.git",tag = "v1.0.0rc1", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git",tag = "v1.0.0rc1", default-features = false }
runtime_primitives = { package = "sr-primitives",  git = "https://github.com/paritytech/substrate.git",tag = "v1.0.0rc1", default-features = false }

[dev-dependencies]
substrate-serializer = {  git = "https://github.com/paritytech/substrate.git",tag = "v1.0.0rc1"}
pretty_assertions = "0.5"

[features]
default = ["std"]
std = [
	"parity-codec-derive/std",
	"parity-codec/std",
	"primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"serde_derive",
	"serde",
]
